[[redirects]]
  from = "/api/reddit/*"
  to = "https://www.reddit.com/:splat"
  status = 200
  force = true

[[headers]]
  for = "/api/reddit/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

